--[[
    File: crates.lua
    Description: Crates plugin configuration
    See: https://github.com/Saecki/crates.nvim
]]
return {
	smart_insert = true,
	insert_closing_quote = true,
	avoid_prerelease = true,
	autoload = true,
	autoupdate = true,
	autoupdate_throttle = 250,
	loading_indicator = true,
	thousands_separator = ".",
	notification_title = "Crates",
	curl_args = { "-sL", "--retry", "1" },
	max_parallel_requests = 80,
	open_programs = { "xdg-open", "open" },
	disable_invalid_feature_diagnostic = false,
	text = {
		loading = "   Loading",
		version = "   %s",
		prerelease = "   %s",
		yanked = "   %s",
		nomatch = "   No match",
		upgrade = "   %s",
		error = "   Error fetching crate",
	},
	popup = {
		autofocus = false,
		hide_on_select = false,
		copy_register = '"',
		border = "rounded",
		show_version_date = false,
		show_dependency_version = true,
		text = {
			title = " %s",
			pill_left = "",
			pill_right = "",
			description = "%s",
			created_label = " created        ",
			created = "%s",
			updated_label = " updated        ",
			updated = "%s",
			downloads_label = " downloads      ",
			downloads = "%s",
			homepage_label = " homepage       ",
			homepage = "%s",
			repository_label = " repository     ",
			repository = "%s",
			documentation_label = " documentation  ",
			documentation = "%s",
			crates_io_label = " crates.io      ",
			crates_io = "%s",
			categories_label = " categories     ",
			keywords_label = " keywords       ",
			version = "  %s",
			prerelease = " %s",
			yanked = " %s",
			version_date = "  %s",
			feature = "  %s",
			enabled = " %s",
			transitive = " %s",
			normal_dependencies_title = " Dependencies",
			build_dependencies_title = " Build dependencies",
			dev_dependencies_title = " Dev dependencies",
			dependency = "  %s",
			optional = " %s",
			dependency_version = "  %s",
			loading = "  ",
		},
		keys = {
			hide = { "q", "<esc>" },
			open_url = { "<cr>" },
			select = { "<cr>" },
			select_alt = { "s" },
			toggle_feature = { "<cr>" },
			copy_value = { "yy" },
			goto_item = { "gd", "K", "<C-LeftMouse>" },
			jump_forward = { "<c-i>" },
			jump_back = { "<c-o>", "<C-RightMouse>" },
		},
	},
}
