--[[
    File: trouble.lua
    Description: Configuration of trouble.nvim
    See: https://github.com/folke/trouble.nvim
]]
local icons = {
  abc                 = "  ",
  array               = "  ",
  arrowReturn         = "  ",
  bigCircle           = "  ",
  bigUnfilledCircle   = "  ",
  bomb                = "  ",
  bookMark            = "  ",
  boolean             = "  ",
  box                 = " 󰅫 ",
  buffer              = "  ",
  bug                 = "  ",
  calculator          = "  ",
  calendar            = "  ",
  caretRight          = "",
  checkSquare         = "  ",
  copilot             = "",
  codeium             = "",
  exit                = " 󰗼 ",
  chevronRight        = "",
  circle              = "  ",
  class               = "  ",
  close               = "  ",
  code                = "  ",
  cog                 = "  ",
  color               = "  ",
  comment             = "  ",
  constant            = "  ",
  constructor         = "  ",
  container           = "  ",
  console             = " 󰞷 ",
  consoleDebug        = "  ",
  cubeTree            = "  ",
  dashboard           = "  ",
  database            = "  ",
  enum                = "  ",
  enumMember          = "  ",
  error               = "  ",
  errorOutline        = "  ",
  errorSlash          = " ﰸ ",
  event               = "  ",
  field               = "  ",
  file                = "  ",
  fileBg              = "  ",
  fileCopy            = "  ",
  fileCutCorner       = "  ",
  fileNoBg            = "  ",
  fileNoLines         = "  ",
  fileNoLinesBg       = "  ",
  fileRecent          = "  ",
  fire                = "  ",
  folder              = "  ",
  folderNoBg          = "  ",
  folderOpen          = "  ",
  folderOpen2         = " 󰉖 ",
  folderOpenNoBg      = "  ",
  forbidden           = " 󰍛 ",
  func                = "  ",
  gear                = "  ",
  gears               = "  ",
  git                 = "  ",
  gitAdd              = "  ",
  gitChange           = " 󰏬 ",
  gitRemove           = "  ",
  hexCutOut           = "  ",
  history             = "  ",
  hook                = " ﯠ ",
  info                = "  ",
  infoOutline         = "  ",
  interface           = "  ",
  key                 = "  ",
  keyword             = "  ",
  light               = "  ",
  lightbulb           = "  ",
  lightbulbOutline    = "  ",
  list                = "  ",
  lock                = "  ",
  m                   = " m ",
  method              = "  ",
  module              = "  ",
  newFile             = "  ",
  note                = " 󰎚 ",
  number              = "  ",
  numbers             = "  ",
  object              = "  ",
  operator            = "  ",
  package             = " 󰏓 ",
  packageUp           = " 󰏕 ",
  packageDown         = " 󰏔 ",
  paint               = "  ",
  paragraph           = " 󰉢 ",
  pencil              = "  ",
  pie                 = "  ",
  pin                 = " 󰐃 ",
  project             = "  ",
  property            = "  ",
  questionCircle      = "  ",
  reference           = "  ",
  ribbon              = " 󰑠 ",
  robot               = " 󰚩 ",
  scissors            = "  ",
  scope               = "  ",
  search              = "  ",
  settings            = "  ",
  signIn              = "  ",
  snippet             = "  ",
  sort                = "  ",
  spell               = " 暈",
  squirrel            = "  ",
  stack               = "  ",
  string              = "  ",
  struct              = "  ",
  table               = "  ",
  tag                 = "  ",
  telescope           = "  ",
  terminal            = "  ",
  text                = "  ",
  threeDots           = " 󰇘 ",
  threeDotsBoxed      = "  ",
  timer               = "  ",
  trash               = "  ",
  tree                = "  ",
  treeDiagram         = " 󰙅 ",
  typeParameter       = "  ",
  unit                = "  ",
  up_hexagon          = " 󰋘 ",
  value               = "  ",
  variable            = "  ",
  warningCircle       = "  ",
  vim                 = "  ",
  warningTriangle     = "  ",
  warningTriangleNoBg = "  ",
  watch               = "  ",
  word                = "  ",
  wrench              = "  ",
}
local trouble = require("trouble")

trouble.setup({
  position = "bottom", -- position of the list can be: bottom, top, left, right
  height = 10, -- height of the trouble list when position is top or bottom
  width = 50, -- width of the list when position is left or right
  icons = true, -- use devicons for filenames
  mode = "document_diagnostics", -- "workspace_diagnostics", "document_diagnostics", "quickfix", "lsp_references", "loclist"
  fold_open = "", -- icon used for open folds
  fold_closed = "", -- icon used for closed folds
  group = true, -- group results by file
  padding = true, -- add an extra new line on top of the list
  action_keys = { -- key mappings for actions in the trouble list
      -- map to {} to remove a mapping, for example:
      -- close = {},
      close = "q", -- close the list
      cancel = "<esc>", -- cancel the preview and get back to your last window / buffer / cursor
      refresh = "r", -- manually refresh
      jump = {"<cr>", "<tab>"}, -- jump to the diagnostic or open / close folds
      open_split = { "<c-x>" }, -- open buffer in new split
      open_vsplit = { "<c-v>" }, -- open buffer in new vsplit
      open_tab = { "<c-t>" }, -- open buffer in new tab
      jump_close = {"o"}, -- jump to the diagnostic and close the list
      toggle_mode = "m", -- toggle between "workspace" and "document" diagnostics mode
      toggle_preview = "P", -- toggle auto_preview
      hover = "K", -- opens a small popup with the full multiline message
      preview = "p", -- preview the diagnostic location
      close_folds = {"zM", "zm"}, -- close all folds
      open_folds = {"zR", "zr"}, -- open all folds
      toggle_fold = {"zA", "za"}, -- toggle fold of current file
      previous = "k", -- preview item
      next = "j" -- next item
  },
  indent_lines = true, -- add an indent guide below the fold icons
  auto_open = false, -- automatically open the list when you have diagnostics
  auto_close = false, -- automatically close the list when you have no diagnostics
  auto_preview = true, -- automatically preview the location of the diagnostic. <esc> to close preview and go back to last window
  auto_fold = false, -- automatically fold a file trouble list at creation
  auto_jump = {"lsp_definitions"}, -- for the given modes, automatically jump if there is only a single result
  signs = {
      -- icons / text used for a diagnostic
      error       = icons.errorOutline,
      warning     = icons.warningTriangleNoBg,
      hint        = icons.lightbulbOutline,
      information = icons.infoOutline,
  },
  use_diagnostic_signs = false -- enabling this will use the signs defined in your lsp client
})
